# docker-compose.yml
version: '2'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    depends_on:
      - db
  receiver:
    build:
      context: .
      dockerfile: Dockerfile.receiver
    ports:
      - "1234:1234"
    depends_on:
      - db
  sender:
    build:
      context: .
      dockerfile: Dockerfile.sender
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
